### ISSUE TITLE
Accessing multi value lookup field does not work

### ISSUE THREAD

**Issue by heikobornholdt** [Plaristote/sharepoint-ruby#25]
I got this error, when I'm trying to access an lookup field with multiple values:
`````ruby
irb(main):008:0> list.items.first.personen_id
NameError: wrong constant name Collection(Edm
	from /Users/heiko/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/sharepoint-ruby-aa63cf5a5d9c/lib/sharepoint-ruby.rb:120:in `const_get'
	from /Users/heiko/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/sharepoint-ruby-aa63cf5a5d9c/lib/sharepoint-ruby.rb:120:in `block in make_object_from_data'
	from /Users/heiko/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/sharepoint-ruby-aa63cf5a5d9c/lib/sharepoint-ruby.rb:120:in `each'
	from /Users/heiko/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/sharepoint-ruby-aa63cf5a5d9c/lib/sharepoint-ruby.rb:120:in `make_object_from_data'
	from /Users/heiko/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/sharepoint-ruby-aa63cf5a5d9c/lib/sharepoint-properties.rb:69:in `get_property'
	from /Users/heiko/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/sharepoint-ruby-aa63cf5a5d9c/lib/sharepoint-properties.rb:27:in `block in add_property'
	from (irb):8:in `<main>'
	from run.rb:13:in `<main>'
`````

**Comment by Plaristote** [comment]
I've merged #24.
